# Generated by Django 5.1.4 on 2025-02-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctor_gender_patient_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.department'),
            preserve_default=False,
        ),
    ]
